### ISSUE TITLE
What is the plan for denodev website update?

### ISSUE THREAD

**Issue by iugo** [denodev/denodev.github.io#1]

**Comment by justjavac** [comment]
On May 13th deno released the first 1.0 official version. I I created 2 tools:

- https://deno.dev/wpt/ Deno web-platform-tests compatibility tables
- https://deno.dev/upgrade-helper/ A web tool to support Deno developers in upgrading their apps.

also a site https://github.com/denodev/typedoc for Deno API Simplified Chinese
